name: server
description: A socket.io server that listens to data sent by a client.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  socket_io: ^1.0.0
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
